/**
   * Created by Bruno Costa 2021-12-23
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Employee = sequelize.define('Employee', {
      NIF: {
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: true,
        allowNull: false
      },
      CC: {
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      expiration_data: {
        type: DataTypes.DATE,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      email: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      photo: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      description: {
        type: DataTypes.TEXT,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      birthdate: {
        type: DataTypes.DATE,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      work_area: {
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      evaluation_date: {
        type: DataTypes.DATE,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      evaluator: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      active: {
        type: DataTypes.TINYINT(1),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      rank: {
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      qualifications: {
        type: DataTypes.TEXT,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      hourly_rate: {
        type: DataTypes.FLOAT,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
    }, {
      tableName: 'Employee',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
          Employee.belongsTo(models.User, {
            foreignKey: 'email',              //on Employee
            targetKey: 'email',  //foreign key
            as:"User_data"
          });
          Employee.belongsTo(models.User, {
            foreignKey: 'evaluator',              //on Employee
            targetKey: 'email',  //foreign key
            as:"Evaluator"
          });
        }
      },
    });

    return Employee;
  };