/**
   * Created by Bruno Costa 2021-12-23
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const User = sequelize.define('User', {
      email: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: true,
        allowNull: false
      },
      first_name: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      last_name: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      hash: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      createdOn: {
        type: DataTypes.DATE,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      role: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      phone_country_code: {
        type: DataTypes.STRING(4),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      phone_code: {
        type: DataTypes.STRING(15),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      telegram: {
        type: DataTypes.TINYINT(1),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      whatsapp: {
        type: DataTypes.TINYINT(1),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'User',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
          User.belongsTo(models.Employee, {
            foreignKey: 'email',              //on User
            targetKey: 'email',  //foreign key
          });
          User.belongsTo(models.Employee, {
            foreignKey: 'email',              //on User
            targetKey: 'evaluator',  //foreign key
          });
        }
      },
    });

    return User;
  };